services:
  - type: web
    name: render-streamlit-demo
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install streamlit
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501